name: activityrank-manager

secrets:
  keys:
    file: ./apps/manager/config/keys.json

configs:
  conf:
    file: ./apps/manager/config/config.json

services:
  mysql:
    container_name: ar.manager-db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./apps/manager/docker/mysql_init:/docker-entrypoint-initdb.d
      - ./apps/manager/docker/data:/var/lib/mysql
      - ./apps/manager/scripts/my.cnf:/etc/mysql/my.cnf
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password

  activityrankmanager:
    container_name: ar.manager
    restart: always
    build: 
      context: .
      dockerfile: ./apps/manager/Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '3005:3000'
    secrets:
      - keys
    configs:
      - conf
