version: '3.3'
name: activityrank-manager

secrets:
  keys:
    file: ./config/keys.json

configs:
  conf:
    file: ./config/config.json

services:
  mysql:
    container_name: activityrank.manager.db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./docker/mysql_init:/docker-entrypoint-initdb.d
      - ./docker/data:/var/lib/mysql
      - ./scripts/my.cnf:/etc/mysql/my.cnf
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password

  activityrankmanager:
    container_name: activityrank.manager
    restart: always
    init: true
    build: .
    image: 'activityrank/manager:dev'
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '3005:3000'
    secrets:
      - keys
    configs:
      - conf
